sudo: false
language: ruby
rvm: 2.3.1
services:
  - mongodb
before_install:
  - ./test/ci/before_install.sh
script: RUBYOPT=W0 bundle exec rake test
before_script:
  - psql -c 'create database searchkick_test;' -U postgres
notifications:
  email:
    on_success: never
    on_failure: change
gemfile:
  - Gemfile
  - test/gemfiles/activerecord42.gemfile
  - test/gemfiles/activerecord41.gemfile
  - test/gemfiles/activerecord40.gemfile
  - test/gemfiles/activerecord32.gemfile
  - test/gemfiles/activerecord31.gemfile
  - test/gemfiles/mongoid2.gemfile
  - test/gemfiles/mongoid3.gemfile
  - test/gemfiles/mongoid4.gemfile
  - test/gemfiles/mongoid5.gemfile
  - test/gemfiles/mongoid6.gemfile
env:
  - ELASTICSEARCH_VERSION=5.1.1
jdk: oraclejdk8
matrix:
  include:
    - gemfile: Gemfile
      env: ELASTICSEARCH_VERSION=1.0.0
      jdk: oraclejdk7
    - gemfile: Gemfile
      env: ELASTICSEARCH_VERSION=1.7.0
      jdk: oraclejdk7
    - gemfile: Gemfile
      env: ELASTICSEARCH_VERSION=2.0.0
      jdk: oraclejdk7
    - gemfile: Gemfile
      env: ELASTICSEARCH_VERSION=2.4.1
      jdk: oraclejdk7
    - gemfile: Gemfile
      env: ELASTICSEARCH_VERSION=5.0.1
      jdk: oraclejdk8
